FROM comutt/scala:2.12.1-8-jdk-jessie_sbt_npm

ADD . /opt/sharedocs/

RUN touch /opt/sharedocs/sharedocsEnv

RUN cd /opt/sharedocs && npm install

RUN mkdir -p /var/sharedocs/upload
VOLUME /var/sharedocs/upload

EXPOSE 8080
CMD ["/opt/sharedocs/sharedocs", "run"]
