FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y scala
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get install -y nodejs
RUN apt-get install -y  build-essential
ADD . /opt/sharedocs/

RUN touch /opt/sharedocs/sharedocsEnv

RUN cd /opt/sharedocs && npm install

RUN mkdir -p /var/sharedocs/upload
VOLUME /var/sharedocs/upload

EXPOSE 8080
CMD ["/opt/sharedocs/sharedocs", "run"]
