#!/bin/bash
# Wrapper for the 'skinny' command.
# Sets up environment variables, etc for running the skinny command on Heroku.
#
# Example usage:
# $ heroku run deployment/heroku/skinny db:migrate heroku

. $(dirname $0)/common.sh

setup_db_env_vars

# Run ../../skinny, passing arguments
$(dirname $(dirname $(dirname $0)))/skinny "$@"
